version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
      - MONGODB_DATA_PATH=/home/vagrant/mongodb/database123
    volumes:
      - /home/vagrant/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
# How to run
# mkdir -pv /home/vagrant/mongodb/database
# sudo docker-compose up -d
