# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.disksize.size = '10GB'
  config.vm.synced_folder "C:/website/", "/home/vagrant/website",
	  owner: "vagrant",
	  group: "vagrant",
    mount_options: ["dmode=775,fmode=664"]
    
  config.vm.network "private_network", ip: "192.168.50.104"

  config.vm.network "forwarded_port", guest: 8040, host: 8040
  config.vm.network "forwarded_port", guest: 8041, host: 8041
  config.vm.network "forwarded_port", guest: 8042, host: 8042
  config.vm.network "forwarded_port", guest: 8043, host: 8043
  config.vm.network "forwarded_port", guest: 8044, host: 8044
  config.vm.network "forwarded_port", guest: 8045, host: 8045

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
#    vb.gui = true
    vb.memory = 2048
	  vb.cpus = 2
  end
  
  config.vm.provision "shell", inline: <<-SHELL
  SHELL
end
