# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.disksize.size = '5GB'
  config.vm.synced_folder "C:/website/Go/src/github.com/minhaz1217/envalyzer", "/home/vagrant/projects/envalyzer",
	  owner: "vagrant",
	  group: "vagrant",
	  mount_options: ["dmode=775,fmode=664"]
  config.vm.network "private_network", ip: "192.168.50.103"

  config.vm.network "forwarded_port", guest: 8010, host: 8010
  config.vm.network "forwarded_port", guest: 5000, host:5000

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
#    vb.gui = true
    vb.memory = 2048
	  vb.cpus = 2
  end
  
  config.vm.provision "shell", inline: <<-SHELL
  SHELL
end
