---
- hosts: "masters, workers"
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
# Step 1
    - name: Install Kubernetes Servers
      shell: |
              sudo apt update
              sudo apt -y upgrade 
# sudo systemctl reboot
# Step 2, intall kubelet, kubeadm and kubectl
    - name: install and configure dependencies
      shell: |
              sudo apt-get update && sudo apt-get install -y apt-transport-https curl
              curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

    - name: Create kubernetes repo file
      file:
        path: "/etc/apt/sources.list.d/kubernetes.list"
        state: "touch"

    - name: Add K8s Source
      blockinfile:
        path: "/etc/apt/sources.list.d/kubernetes.list"
        block: |
              deb https://apt.kubernetes.io/ kubernetes-xenial main

    - name: install kubernetes
      shell: |
              sudo apt-get update
              sudo apt -y install kubelet kubeadm kubectl
              sudo apt-mark hold kubelet kubeadm kubectl
# Step 3: Disable swap
    - name: disable swap
      shell: |
              sudo swapoff -a
              sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    - name: Enable kernel modules
      shell: |
              sudo modprobe overlay
              sudo modprobe br_netfilter

    - name: Set system configurations for Kubernetes networking
      file:
        path: "/etc/sysctl.d/99-kubernetes-cri.conf"
        state: "touch"

    - name: Add conf for containerd
      blockinfile:
        path: "/etc/sysctl.d/99-kubernetes-cri.conf"
        block: |
                net.bridge.bridge-nf-call-ip6tables = 1
                net.bridge.bridge-nf-call-iptables = 1
                net.ipv4.ip_forward = 1

    - name: Apply new settings
      command: sudo sysctl --system

# Step 4: install docker
    - name: Add repo and Install docker
      shell: |
              sudo apt-get update && sudo apt install -y curl gnupg2 software-properties-common apt-transport-https ca-certificates
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
              sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
              sudo apt update
              sudo apt install -y containerd.io docker-ce docker-ce-cli

    - name: Create required directories
      shell: |
              sudo mkdir -p /etc/systemd/system/docker.service.d

    - name: Create daemon json config file
      file:
        path: "/etc/docker/daemon.json"
        state: "touch"   

    - name: Add conf for containerd
      blockinfile:
        path: "/etc/docker/daemon.json"
        block: |
                {
                  "exec-opts": ["native.cgroupdriver=systemd"],
                  "log-driver": "json-file",
                  "log-opts": {
                    "max-size": "100m"
                  },
                  "storage-driver": "overlay2"
                }
    - name: Add repo and Install docker
      shell: |
              sudo systemctl daemon-reload 
              sudo systemctl restart docker
              sudo systemctl enable docker
