---
- name: Deploying easycommerce
  hosts: vagrant
  become: yes
  tasks:
    # installing docker
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl','gnupg', 'lsb-release']

    - name: Add Docker GPG apt Key
      apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present

    - name: Add Docker Repository
      apt_repository:
       repo: deb https://download.docker.com/linux/ubuntu bionic stable
       state: present

    - name: Update apt and install docker-ce, cli, containerd
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'docker-ce', 'docker-ce-cli', 'containerd.io']
  
    # # installing git
    # - name: install git package
    #   apt:
    #     name: git
    #     update_cache: yes

    # - name: Created the ecommerce directory
    #   file:
    #     path: /home/projects/easycommerce
    #     state: directory
    #     mode: '0755'
    # - name: Cloning git
    #   git:
    #     repo: 'https://{{ githubuser | urlencode }}:{{ githubpassword | urlencode }}@github.com/minhaz1217/EasyCommerce.git'
    #     dest: /home/projects/easycommerce
    #     clone: yes
    #     update: yes
    #   async: 1000
    #   poll: 0
    #   register: git_cloning
    # # trying to show status while git clones
    # - name: 'Git cloning status'
    #   async_status:
    #     jid: "{{ git_cloning.ansible_job_id }}"
    #   register: job_result
    #   until: job_result.finished
    #   retries: 100

    # # installing pip
    # - name: Install pip3
    #   apt:
    #     name: python3-pip
    #     update_cache: yes

    # # installing docker py
    # - name: Install python docker-ce
    #   pip: name=docker-py

    - name: Build the easycommerce_image
      docker_image:
        name: easycommerce_image
        build:
          path: /home/projects/easycommerce
        source: build

    # - name: Create a data container
    #   community.docker.docker_container:
    #     name: easycommerce
    #     image: myimage
    #     published_ports: 5000:80
    #     state: started
