---

all:
  children:
    vagrant:
      hosts:
        local1:
          # ansible_host: 192.168.50.101
          ansible_host: 192.168.50.102
      vars:
        ansible_port: 22
        ansible_user : vagrant
        ansible_password : vagrant
        ansible_python_interpreter: "/usr/bin/python3"