---

all:
  children:
    vagrant:
      hosts:
        local1:
          ansible_host: 192.168.50.103
        local2:
          ansible_host: 192.168.50.104
        local3:
          ansible_host: 192.168.50.100

      vars:
        ansible_port: 22
        ansible_user : vagrant
        ansible_password : vagrant
        # ansible_private_key_file: ./keys/public_key.ppk

# all:
#   hosts:
#     local1:
#       ansible_host: 127.0.0.1
#       ansible_port: 2222
#       ansible_user : vagrant
#       ansible_password : vagrant
#       ansible_private_key_file: ./keys/public_key.ppk
